// This file is automatically generated and managed by the system.
// Do not modify this file manually.

export const firebaseConfig = {
  apiKey: 'AIzaSyC2_1fJd3T1gX5aY6h7Z8c9V0b2E4f3DgI',
  authDomain: 'citamedicafacil.firebaseapp.com',
  projectId: 'citamedicafacil',
  storageBucket: 'citamedicafacil.appspot.com',
  messagingSenderId: '1011296435123',
  appId: '1:1011296435123:web:f8a7c2957b4b3b89b5a9c6',
};
