// This file is automatically generated and managed by the system.
// Do not modify this file manually.

export const firebaseConfig = {
  apiKey: "YOUR_API_KEY",
  authDomain: 'citamedicafacil.firebaseapp.com',
  projectId: 'citamedicafacil',
  storageBucket: 'citamedicafacil.appspot.com',
  messagingSenderId: '1011296435123',
  appId: '1:1011296435123:web:f8a7c2957b4b3b89b5a9c6',
};
