// This file is automatically generated and managed by the system.
// Do not modify this file manually.

export const firebaseConfig = {
  projectId: 'citasfull-ok-22108253-af2f0',
  appId: '1:821094072226:web:7ae864de2eb3f42debbcfb',
  apiKey: 'AIzaSyDlHYibUZf-0zIiMDKXAM34vQggoye10YI',
  authDomain: 'citasfull-ok-22108253-af2f0.firebaseapp.com',
  measurementId: '',
  messagingSenderId: '821094072226',
};
